USE [master]
GO
/****** Object:  Database [GESTAO]    Script Date: 16/06/2023 19:27:51 ******/
CREATE DATABASE [GESTAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GESTAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GESTAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GESTAO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GESTAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GESTAO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GESTAO] SET ARITHABORT OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GESTAO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GESTAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GESTAO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GESTAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GESTAO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GESTAO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GESTAO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GESTAO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GESTAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GESTAO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GESTAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GESTAO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GESTAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GESTAO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GESTAO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GESTAO] SET  MULTI_USER 
GO
ALTER DATABASE [GESTAO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GESTAO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GESTAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GESTAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GESTAO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GESTAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GESTAO] SET QUERY_STORE = OFF
GO
USE [GESTAO]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[CPF] [varchar](15) NULL,
	[RG] [varchar](15) NULL,
	[Email] [varchar](200) NULL,
	[Fone] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fornecedor]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fornecedor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[Fone] [varchar](15) NULL,
	[Email] [varchar](200) NULL,
	[Site] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grupo_com_Usuario_N_N]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grupo_com_Usuario_N_N](
	[cod_usuario] [int] NOT NULL,
	[cod_GrupoUsuario] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[id_GrupoUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NomeGrupo] [varchar](50) NOT NULL,
 CONSTRAINT [PK__GrupoUsu__03AB54E489FEDE10] PRIMARY KEY CLUSTERED 
(
	[id_GrupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[id_Permissao] [int] NOT NULL,
	[Descricao] [varchar](150) NOT NULL,
 CONSTRAINT [PK__Permissa__77C99B4F34B95520] PRIMARY KEY CLUSTERED 
(
	[id_Permissao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao_com_Grupo]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao_com_Grupo](
	[cod_Permissao] [int] NOT NULL,
	[cod_GrupoUsuario] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 16/06/2023 19:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NOT NULL,
	[nome_Usuario] [varchar](20) NOT NULL,
	[data_Nascimento] [varchar](10) NOT NULL,
	[cpf_Usuario] [varchar](15) NOT NULL,
	[senha] [varchar](20) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[ativo] [bit] NOT NULL,
 CONSTRAINT [PK__Usuario__8E901EAAE40E66B2] PRIMARY KEY CLUSTERED 
(
	[id_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N]  WITH CHECK ADD  CONSTRAINT [fk_com_grupo] FOREIGN KEY([cod_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([id_GrupoUsuario])
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N] CHECK CONSTRAINT [fk_com_grupo]
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N]  WITH CHECK ADD  CONSTRAINT [fk_com_usuario] FOREIGN KEY([cod_usuario])
REFERENCES [dbo].[Usuario] ([id_Usuario])
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N] CHECK CONSTRAINT [fk_com_usuario]
GO
ALTER TABLE [dbo].[Permissao_com_Grupo]  WITH CHECK ADD  CONSTRAINT [fk_grupousuario] FOREIGN KEY([cod_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([id_GrupoUsuario])
GO
ALTER TABLE [dbo].[Permissao_com_Grupo] CHECK CONSTRAINT [fk_grupousuario]
GO
ALTER TABLE [dbo].[Permissao_com_Grupo]  WITH CHECK ADD  CONSTRAINT [fk_permissao] FOREIGN KEY([cod_Permissao])
REFERENCES [dbo].[Permissao] ([id_Permissao])
GO
ALTER TABLE [dbo].[Permissao_com_Grupo] CHECK CONSTRAINT [fk_permissao]
GO
USE [master]
GO
ALTER DATABASE [GESTAO] SET  READ_WRITE 
GO
