USE [master]
GO
/****** Object:  Database [GESTAO2]    Script Date: 09/04/2023 13:24:24 ******/
CREATE DATABASE [GESTAO2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GESTAO2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GESTAO2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GESTAO2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GESTAO2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GESTAO2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GESTAO2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GESTAO2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GESTAO2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GESTAO2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GESTAO2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GESTAO2] SET ARITHABORT OFF 
GO
ALTER DATABASE [GESTAO2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GESTAO2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GESTAO2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GESTAO2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GESTAO2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GESTAO2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GESTAO2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GESTAO2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GESTAO2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GESTAO2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GESTAO2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GESTAO2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GESTAO2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GESTAO2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GESTAO2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GESTAO2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GESTAO2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GESTAO2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GESTAO2] SET  MULTI_USER 
GO
ALTER DATABASE [GESTAO2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GESTAO2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GESTAO2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GESTAO2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GESTAO2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GESTAO2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GESTAO2] SET QUERY_STORE = ON
GO
ALTER DATABASE [GESTAO2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GESTAO2]
GO
/****** Object:  Table [dbo].[Cidade]    Script Date: 09/04/2023 13:24:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cidade](
	[Id_Cidade] [int] IDENTITY(1,1) NOT NULL,
	[NomeCidade] [varchar](100) NOT NULL,
	[cod_Estado] [int] NOT NULL,
 CONSTRAINT [PK_Cidade] PRIMARY KEY CLUSTERED 
(
	[Id_Cidade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Endereco]    Script Date: 09/04/2023 13:24:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Endereco](
	[Id_Endereco] [int] IDENTITY(1,1) NOT NULL,
	[TipoLogradouro] [varchar](50) NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[NumeroCasa] [varchar](10) NOT NULL,
	[Quadra] [varchar](10) NULL,
	[Lote] [varchar](10) NULL,
	[CEP] [varchar](11) NULL,
	[cod_Cidade] [int] NOT NULL,
 CONSTRAINT [PK_Endereco] PRIMARY KEY CLUSTERED 
(
	[Id_Endereco] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estado]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[Id_Estado] [int] IDENTITY(1,1) NOT NULL,
	[NomeEstado] [varchar](100) NULL,
	[Sigla] [varchar](3) NULL,
	[cod_Pais] [int] NULL,
 CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED 
(
	[Id_Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grupo_com_Usuario_N_N]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grupo_com_Usuario_N_N](
	[cod_usuario] [int] NOT NULL,
	[cod_GrupoUsuario] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[id_GrupoUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NomeGrupo] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_GrupoUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pais]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pais](
	[Id_Pais] [int] IDENTITY(1,1) NOT NULL,
	[NomePais] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED 
(
	[Id_Pais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[id_Permissao] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_Permissao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao_com_Grupo]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao_com_Grupo](
	[cod_Permissao] [int] NOT NULL,
	[cod_GrupoUsuario] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pessoa]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pessoa](
	[Id_Pessoa] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](60) NOT NULL,
	[Sobrenome] [varchar](100) NULL,
	[DataDeNascimento] [varchar](11) NULL,
	[CPF] [varchar](15) NULL,
	[RG] [varchar](20) NULL,
	[OrgaoExpedidorRG] [varchar](100) NULL,
	[cod_EstadoRG] [int] NULL,
	[DataExpedicaoRG] [varchar](11) NULL,
	[cod_Endereco] [int] NULL,
	[Email] [varchar](100) NULL,
 CONSTRAINT [PK_Pessoa] PRIMARY KEY CLUSTERED 
(
	[Id_Pessoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefone]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefone](
	[Id_Telefone] [int] NOT NULL,
	[NumeroTelefone] [varchar](20) NOT NULL,
	[Cod_Pessoa] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 09/04/2023 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[nome_Usuario] [varchar](20) NOT NULL,
	[senha] [varchar](20) NOT NULL,
	[ativo] [bit] NOT NULL,
	[Funcao] [varchar](100) NULL,
	[Cargo] [varchar](100) NULL,
	[cod_Pessoa] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[senha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cidade]  WITH CHECK ADD FOREIGN KEY([cod_Estado])
REFERENCES [dbo].[Estado] ([Id_Estado])
GO
ALTER TABLE [dbo].[Endereco]  WITH CHECK ADD FOREIGN KEY([cod_Cidade])
REFERENCES [dbo].[Cidade] ([Id_Cidade])
GO
ALTER TABLE [dbo].[Estado]  WITH CHECK ADD FOREIGN KEY([cod_Pais])
REFERENCES [dbo].[Pais] ([Id_Pais])
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N]  WITH CHECK ADD  CONSTRAINT [fk_com_grupo] FOREIGN KEY([cod_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([id_GrupoUsuario])
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N] CHECK CONSTRAINT [fk_com_grupo]
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N]  WITH CHECK ADD  CONSTRAINT [fk_com_usuario] FOREIGN KEY([cod_usuario])
REFERENCES [dbo].[Usuario] ([id_Usuario])
GO
ALTER TABLE [dbo].[Grupo_com_Usuario_N_N] CHECK CONSTRAINT [fk_com_usuario]
GO
ALTER TABLE [dbo].[Permissao_com_Grupo]  WITH CHECK ADD  CONSTRAINT [fk_grupousuario] FOREIGN KEY([cod_GrupoUsuario])
REFERENCES [dbo].[GrupoUsuario] ([id_GrupoUsuario])
GO
ALTER TABLE [dbo].[Permissao_com_Grupo] CHECK CONSTRAINT [fk_grupousuario]
GO
ALTER TABLE [dbo].[Permissao_com_Grupo]  WITH CHECK ADD  CONSTRAINT [fk_permissao] FOREIGN KEY([cod_Permissao])
REFERENCES [dbo].[Permissao] ([id_Permissao])
GO
ALTER TABLE [dbo].[Permissao_com_Grupo] CHECK CONSTRAINT [fk_permissao]
GO
ALTER TABLE [dbo].[Pessoa]  WITH CHECK ADD FOREIGN KEY([cod_Endereco])
REFERENCES [dbo].[Endereco] ([Id_Endereco])
GO
ALTER TABLE [dbo].[Telefone]  WITH CHECK ADD FOREIGN KEY([Cod_Pessoa])
REFERENCES [dbo].[Pessoa] ([Id_Pessoa])
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD FOREIGN KEY([cod_Pessoa])
REFERENCES [dbo].[Pessoa] ([Id_Pessoa])
GO
USE [master]
GO
ALTER DATABASE [GESTAO2] SET  READ_WRITE 
GO
